{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "didnotreadit.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "didnotreadit.secretName" . }}
  labels:
    {{- include "didnotreadit.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.app.sessionSecret | default (index (($existingSecret).data | default dict) "session-secret" | default "" | b64dec) | default (randAlphaNum 32) | quote }}
  {{- if not .Values.postgresql.enabled }}
  database-url: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
