{{- if and .Values.app.ingress.tls.enabled .Values.app.ingress.tls.crt .Values.app.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.ingress.tls.secretName | default (printf "%s-tls" (include "didnotreadit.fullname" .)) }}
  labels:
    {{- include "didnotreadit.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.app.ingress.tls.crt }}
  tls.key: {{ .Values.app.ingress.tls.key }}
{{- end }}
