apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: didnotreadit
spec:
  title: did not read it
  icon: https://github.com/ivolgin-lab.png
  applicationUrl: 'repl{{ if ConfigOptionEquals "ingress_enabled" "1" }}repl{{ if ConfigOptionEquals "ingress_tls_enabled" "1" }}https://repl{{ else }}http://repl{{ end }}repl{{ ConfigOption "ingress_hostname" }}repl{{ end }}'
  statusInformers:
    - deployment/didnotreadit-app
    - statefulset/didnotreadit-postgresql
    - deployment/didnotreadit-sdk
  ports:
    - serviceName: didnotreadit-app
      servicePort: 3000
      localPort: 8888
      applicationUrl: 'repl{{ if ConfigOptionEquals "ingress_enabled" "1" }}repl{{ if ConfigOptionEquals "ingress_tls_enabled" "1" }}https://repl{{ else }}http://repl{{ end }}repl{{ ConfigOption "ingress_hostname" }}repl{{ end }}'
